from tkinter import *

window=Tk()
window.title("Student Details")
window.geometry("450x550")

def __init__(self):
    save_info()

def save_info():
    forms_info = forms.get()
    fast_info = fast.get()
    go_info = go.get()
    fsd_info = fsd.get()
    print("Name :",forms_info)
    print("Address :",fast_info)
    print("E-Mail :",go_info)
    print("Phone-No :",fsd_info)
    print("Details have Saved! in the text file..")
    f=open("detailling.txt","a")
    f.write("------------------------")
    f.write("\nDetails have Saved!")
    f.write("\nYour Details are :\n")
    f.write("Name : %s"%forms_info)
    f.write("\nAddress :%s"%fast_info)
    f.write("\nE-Mail :%s"%go_info)
    f.write("\nPhone-No :%s"%str(fsd_info))
    f.write("\n-----------------------")
    f.close()

    msg = Message(window,text="Details have saved!",font = "Arial 10 normal")
    msg.pack()

   # with open("detailling.txt","r") as f:
        #disp = Label(window,text=f.read(),font = "Arial 12 normal")
        #disp.pack()
     
    forms.delete(0,END)
    fast.delete(0,END)
    go.delete(0,END)
    fsd.delete(0,END)

form = Label(window, text = "WELCOME TO THE STUDENT FORM!",font = "Times 16 bold",fg = "dark green",bg="black",width = "50")
form.pack()
forms = Label(window,text= "Name :",font ="Verdana 12 bold",fg = "blue")
forms.pack()
forms = StringVar()
forms = Entry(window,textvariable = forms,font = "Arial 12 normal")
forms.pack(ipady = 5)
fast = Label(window,text ="Addrerss:",font ="Verdana 12 bold",fg = "blue")
fast.pack()
fast = StringVar()
fast = Entry(window,textvariable = fast,font = "Arial 10 normal")
fast.pack(ipady = 16,ipadx = 16)
go = Label(window,text ="E-Mail :",font = "Verdana 12 bold",fg = "blue")
go.pack()
go = StringVar()
go = Entry(window,textvariable = go,font = "Arial 12 normal")
go.pack(ipady = 5)
fsd = Label(window,text = "Phone-No:",font ="Verdana 12 bold",fg = "blue")
fsd.pack()
fsd = IntVar()
fsd = Entry(window,textvariable = fsd,font = "Arial 12 normal")
fsd.pack(ipady = 5)
Button(window,text = "Submit",font = "Times 12 bold",command = save_info,bg = "green",fg = "blue").pack()
window.mainloop()
